# Generated by Django 3.0.2 on 2020-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='set_for_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='set_for_type',
            field=models.CharField(default='day', max_length=50),
        ),
    ]
