# Generated by Django 3.0.2 on 2020-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200320_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
