# Generated by Django 3.0.2 on 2020-04-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_goal_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
